<a href="https://colab.research.google.com/github/roklp/MLP34/blob/main/240103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

199pg Chapter 10 따로 혼자 ㄱㄱ

## Numpy
- 선형대수,행렬 / 수치연산과 관련된 라이브러리
- Numpy 기반으로 통계,머신러닝 등등

In [2]:
import numpy as np # Numpy 라이브러리 불러오기

print(np.__version__)

1.23.5


In [4]:
#import streamlit as st

#print(st.__version__)  # 라이브러리 설치가 안되어있서

ModuleNotFoundError: ignored

In [5]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [6]:
a1.dtype

dtype('int64')

In [7]:
np.array([0.5, 2, 0.01, 8]).dtype

dtype('float64')

## Numpy 배열 생성

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10)  # 1차원 배열

In [11]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.arange(12).reshape(2, 2, 3) # reshape(a, b, c) a*b*c 가 arrange(n) n 을 넘기면 안됨

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [13]:
b1 = np.arange(12).reshape(2, 2, 3)
b1.shape

(2, 2, 3)

In [14]:
# 범위의 시작과 끝 정하기 배열 생성

np.linspace(0, 10, 5) # 0 과 10 사이에 숫자 5개 뽑아주세요

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, np.pi, 20)

In [ ]:
np.zeros(10)


In [ ]:
np.zeros((2,2))

In [ ]:
# 단위행렬

arr_I = np.eye(3)
arr_I

In [ ]:
arr_I.shape

In [ ]:
np.array(['1.5', '0.62'])

In [ ]:
# astype() # pandas 에서 사용가능

arr = np. array(['1.5', '0.62'])
num_arr = arr.astype(float)
num_arr.dtype

In [ ]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_f1 = num_f1.astype(int)
num_f1

In [ ]:
# 난수(무작위로 숫자 추출)

np.random.rand(2,3)

In [ ]:
np.random.randint(1,100, 10) # 1부터100 중에 랜덤으로 10개 뽑아줘

In [ ]:
import random

def lotte_numbers():



In [ ]:
import random

def numbers():
    numbers = []
    while len(numbers) < 6:
        number = random.randint(1, 100)
        if number not in numbers:
            numbers.append(number)
    return sorted(numbers)

result_numbers = numbers()
print("당첨 번호: ", result_numbers)



## 배열의 연산

In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

## 비교연산

In [ ]:
arr1 > 20

## 통계 연산
- NumPy, 합, 평균, 표준 편차, 분산, 최솟값, 최댓값, 누적합, 누적 곱 메서드가 있음
 + 기술 통계랑 (Descriptive,Statistics) : 현재 데이터 상태를 표현(=묘사,Describe)한다
- 통계
 + 모수 통계
 + 비모수 통계
 + 베이지안 통계
 - 근데 다 필요없고 평균이 전부임


In [16]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [17]:
arr3.sum()

10

In [18]:
arr3.mean()

2.0

In [19]:
arr3.std() # 표준편차

1.4142135623730951

In [20]:
arr3.var() # 분산

2.0

## 누적합과 누적곱
- cumsum() : 누적합
- cimprod() : 누적곱

In [21]:
arr4 = np.arange(1, 5)
arr4

array([1, 2, 3, 4])

In [22]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [23]:
arr4.cumprod()

array([ 1,  2,  6, 24])

## 행렬 연산
- 선형 대수(Linear Algebra)를 위한 2차원 배열 연산도 지원
- 행렬곱, 전치행렬, 역행렬, 형렬식

In [24]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [25]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [26]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [27]:
A.transpose()

array([[0, 2],
       [1, 3]])

## 배열의 인덱싱/슬라이싱
- string, list, tuple과 동일한 방법으로 접근

In [28]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [29]:
a1[4]

40

In [30]:
# 50을 70으로 변경하고 싶음

a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [35]:
# 리스트 통해서 추출

a1[[0, 2, 4]]

idx_list = [0, 2, 4]
a1[idx_list]

array([ 0, 20, 40])

In [37]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [46]:
a2[0, 0]

10

In [47]:
# 90을 95로 변경

a2[2, 2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [48]:
a2[0, 2]

30

In [49]:
a2[0, 1]

20

In [50]:
a2[2, 2]

95

In [51]:
a2[2, 1]

80

In [52]:
a2[0]

array([10, 20, 30])

In [56]:
a2[0] = [1, 2, 3]
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [70, 80, 95]])

In [58]:
a2[0] = np.array([1, 2, 3])
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [70, 80, 95]])

In [61]:
a2

array([[ 1,  2,  3],
       [40, 50, 60],
       [70, 80, 95]])

In [62]:
a2[[0, 2], [0, 1]]


array([ 1, 80])

In [63]:
a2[0, 2]

3

# 배열 조건문
- pandas 문법과 유사

In [64]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [65]:
a[a>3]

array([4, 5, 6])

In [66]:
[a>3]

[array([False, False, False,  True,  True,  True])]

In [67]:
a % 2 == 0

array([False,  True, False,  True, False,  True])

## 배열의 슬라이싱

In [68]:
b1 = np.array([0, 1, 2, 3, 4, 5])
b1[1:4]

array([1, 2, 3])

In [69]:
b1[:3]

array([0, 1, 2])

In [70]:
b1[2:]

array([2, 3, 4, 5])

In [71]:
b1 [0:4:2]

array([0, 2])

In [73]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0,  1, 25, 35, 45,  5])

In [74]:
b1[3:6] = 60
b1

array([ 0,  1, 25, 60, 60, 60])

In [75]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [76]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [77]:
b2[1:, 1:]

array([[50, 60],
       [80, 90]])

In [78]:
b2[0]

array([10, 20, 30])

In [79]:
b2[1][0:2]

array([40, 50])

In [80]:
b2[0][1:2]

array([20])

In [81]:
b2[1][1:2]

array([50])

## Numpy 조건문
- np.where : 단일 조건문
- np.select : 다중 조건문

In [82]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
# 0, 1, 2, 3, 4, 50, 60, 70, 80, 90

np.where(arr < 5, arr, arr * 10 )

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [84]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
# 100, 101, 2, 3, 4, 5, 6, 7, 8, 9
# 2 미만 일 때는 100을 더할것
# 5 초과 일 때는 * 2 를 할것

# 조건식과 대응하는 결과를 리스트로 만들기

cond_list = [arr > 5, arr < 2]
choice_list = [arr * 2, arr + 100]

np.select(cond_list, choice_list, default = arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])